Fix NPEs in SavedRequest
apache/tomee pull request #1328
Opened 2024-07-27 00:43 UTC by mpuening

2024-07-27 00:50 UTC, mpuening commented
Stack trace fetching "Content-Type" header:

 java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "java.util.Map.get(Object)" is null
	org.apache.tomee.security.http.SavedRequest$1.getHeader(SavedRequest.java:110)
	jakarta.servlet.http.HttpServletRequestWrapper.getHeader(HttpServletRequestWrapper.java:83)
	com.sun.faces.context.RequestHeaderMap.get(RequestHeaderMap.java:48)
	com.sun.faces.context.RequestHeaderMap.get(RequestHeaderMap.java:32)
	java.base/java.util.Collections$UnmodifiableMap.get(Collections.java:1656)
	jakarta.faces.application.ViewHandler.calculateCharacterEncoding(ViewHandler.java:363)
	jakarta.faces.application.ViewHandler.initView(ViewHandler.java:236)
	com.sun.faces.application.view.MultiViewHandler.initView(MultiViewHandler.java:110)
	jakarta.faces.application.ViewHandlerWrapper.initView(ViewHandlerWrapper.java:81)
	com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:95)
	com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
	jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:67)

2024-07-27 04:06 UTC, jungm commented on tomee/tomee-security/src/main/java/org/apache/tomee/security/http/SavedRequest.java
> +                    return null;
Not sure if we should turn an empty header value into null implicitly, I'll check later what other implementations of HttpServletRequest do in that case

2024-07-27 12:39 UTC, jungm requested changes
Nice PR!
I've commented a few minor details I would still like to see changed. Also `getHeaderNames()` is not included in your changes

2024-07-27 12:39 UTC, jungm commented on tomee/tomee-security/src/main/java/org/apache/tomee/security/http/SavedRequest.java
> +                    return null;
Servlet 6.0 spec says:
> Returns the value of the specified request header as a String. If the request did not include a header of the specified name, this method returns null. If there are multiple headers with the same name, this method returns the first head in the request. The header name is case insensitive. You can use this method with any request header.

IMO this means we must not alter the header value if it is present. From a quick glance this is also how tomcat/jetty work

2024-07-27 12:39 UTC, jungm commented on tomee/tomee-security/src/main/java/org/apache/tomee/security/http/SavedRequest.java
> +                List<String> header = headers.get(name);
in `getHeaders(String)` you assume `headers`may be null, this check is missing here

2024-07-28 11:00 UTC, jungm commented
@mpuening can you fix `getHeaderNames()` as well? Then it should look good I think

2024-07-28 18:25 UTC, jungm approved these changes

2024-07-28 18:54 UTC, rzo1 approved these changes

2024-08-05 16:42 UTC, merged